#!/usr/bin/env python
# coding: utf-8

# Copyright (C) USC Information Sciences Institute
# Author: Vladimir M. Zaytsev <zaytsev@usc.edu>
# URL: <http://nlg.isi.edu/>
# For more information, see README.md
# For license information, see LICENSE


import sys
import logging
import argparse

from mokujin.index import TripleReader
from mokujin.index import DepTupleIndex


if __name__ == "__main__":

    logging.basicConfig(level=logging.INFO)

    parser = argparse.ArgumentParser()
    parser.add_argument("-i", "--input", default=None, type=str, help="Source CSV file with triples, generated by "
                                                                      "findtriples.py script")
    parser.add_argument("-o", "--out_dir", default="triple-store-index", type=str, help="Triple index directory")
    parser.add_argument("-mf", "--min_freq", default=5, type=int, help="Triple minimum frequency to be stored in index")
    args = parser.parse_args()

    i_file = sys.stdout if args.input is None else open(args.input, "rb")
    o_dir = args.out_dir

    logging.info("INPUT FILE: %r" % i_file)
    logging.info("OUT DIR: %r" % o_dir)
    logging.info("MIN FREQ: %d" % args.min_freq)

    reader = TripleReader()


    i_triples = reader.iter_triples(i_file)
    DepTupleIndex.create(index_root=o_dir, tuples=i_triples, freq_threshold=args.min_freq)

    logging.info("DONE")
